# Basic necessities
brew 'zsh'
brew 'zsh-completions'
brew 'starship'
brew 'bash'
brew 'git'
brew 'nvim'
brew 'tmux'
brew 'pwgen'
brew 'wget'
brew 'curl'
brew 'rsync'
brew 'telnet'
brew 'dust'
# TODO: pick a dotfile manager
# brew 'chezmoi'
# brew 'yadm'
cask '1password/tap/1password-cli'
brew 'atuin'

# Fonts!
cask "font-victor-mono"

# Helpers for dotfiles related stuff
brew 'moreutils'
brew 'keychain'
brew 'icdiff'
brew 'git-delta'
brew 'bat'
brew 'eza'
brew 'shellcheck'

# For development
brew 'go'
brew 'asdf'
## Dev utils
brew 'ctags'
brew 'jq'
brew 'gojq'
brew 'ijq'
brew 'ripgrep'
brew 'make'
brew 'dos2unix'
tap 'danielgtaylor/restish'
brew 'restish'
## Ops utils
brew 'sipcalc'
brew 'rename'
brew 'doggo'
brew 'awscli'
cask 'aws-vault'
brew 'hadolint'
brew 'sshuttle'
brew 'magic-wormhole'
brew '7zip'

# art related stuff
brew 'ffmpeg'
brew 'imagemagick'

# Apps
cask 'firefox'
cask 'google-chrome'
cask 'kitty'
cask 'tunnelblick'
cask 'macvim'
cask 'sourcetree'
cask 'rectangle'
cask 'karabiner-elements'
cask 'remember-the-milk'
cask 'obsidian'
cask 'orbstack'
cask 'tableplus'
cask 'plex'
cask 'plexamp'
cask 'spotify'
cask 'tidal'
cask 'steam'
cask 'maccy'
cask 'discord'
cask 'telegram'
cask 'stats'

# Other fun stuff
brew 'cowsay'
brew 'fortune'
brew 'graphviz'
brew 'toilet'
brew 'figlet'
brew 'lolcat'
