[global]
cache-dir = "~/.cache/rumdl"

disable = [
  # Show command output in documentation
  "MD014",
  # Keep your document organized with one main title
  "MD025",
  # Start Your Document with a Clear Title
  "MD041",
  # URLs should be formatted as links
  "MD034",
]

[MD013]
line-length = 0
reflow = true
reflow-mode = "sentence-per-line"

[MD004]
style = "consistent"
