add_newline = true
command_timeout = 2000

format = """
┌─ $status$time ── $directory──┐
│  $username$git_branch$git_status$git_state$ruby$python$nodejs$terraform$golang$rust
└─ $hostname$shell ── """

[status]
disabled = false

[time]
disabled = false
format = "[$time]($style)"
time_format = "%R %a, %b %e"

[shell]
disabled = false
format = "[$indicator]($style)"
bash_indicator = "\\$"
zsh_indicator = "%%"

[directory]
truncation_length = 0
truncate_to_repo = false

[hostname]
ssh_only = false
format = "[$hostname]($style)"

[username]
format = "[(u:$user) ]($style)"

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([\($all_status$ahead_behind\)]($style) )'
style = ""
up_to_date = "✔"
ahead = "↑${count}"
diverged = "⇕↑${ahead_count}↓⇣${behind_count}"
behind = "↓${count}"
stashed = ""
untracked = "…"
conflicted = "[✖${count}](red)"
modified = "[✚${count}](blue)"
staged = "[●${count}](red)"

[nodejs]
format = "[$symbol($version )]($style)"
symbol = "js "

[ruby]
format = "[$symbol($version )]($style)"

[python]
format = "[$symbol($version )]($style)"

[terraform]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"

[rust]
format = "[$symbol($version )]($style)"
