add_newline = true
command_timeout = 2000

format = """
┌─ $status$time ── ${custom.directory}──┐
│  ${custom.username}$git_branch$git_status$git_state$ruby$python${custom.python_env}$nodejs$terraform$golang$rust
└─ $hostname$shell ── """

[status]
disabled = false

[time]
disabled = false
format = "[$time]($style)"
style = "bold cyan"
time_format = "%R %a, %b %e"

[shell]
disabled = false
format = "[$indicator]($style)"
bash_indicator = "\\$"
zsh_indicator = "%"

[directory]
truncation_length = 0
truncate_to_repo = false

[custom.directory]
when = "true"
format = "[$output]($style) "
command = "pwd"
style = "bold cyan"

[hostname]
ssh_only = false
format = "[$hostname]($style)"

[custom.username]
when = "test $USER != 'clayton'"
format = "[\\(u:$output\\)]($style) "
command = "echo $USER"
style = "bold red"

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([\($all_status$ahead_behind\)]($style) )'
style = ""
up_to_date = "✔"
ahead = "↑${count}"
diverged = "[◆↑${ahead_count}↓${behind_count}](red)"
behind = "↓${count}"
stashed = ""
untracked = "…"
renamed = "[↻${count}](bold yellow)"
deleted = "[✘${count}](bold red)"
conflicted = "[✖${count}](red)"
modified = "[✚${count}](blue)"
staged = "[●${count}](red)"

[nodejs]
format = "[$symbol($version )]($style)"
symbol = "js "
style = "bold yellow"

[ruby]
format = "[$symbol($version )]($style)"

[python]
format = "[$symbol($version )]($style)"
style = "bold green"

[custom.python_env]
when = 'test -n "$VIRTUAL_ENV"'
format = "[\\($output\\)]($style) "
command = "basename $VIRTUAL_ENV"
style = "bold green"

[terraform]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"

[rust]
format = "[$symbol($version )]($style)"
