#!/bin/sh
# Default to 7 days
TIMEOUT=$((86400 * 7))
DEFAULT_IMG='/home/clayton/Pictures/Wallpaper/bonespin.png'

current_cache_file() {
  echo $(find /tmp -readable -type f -name 'papers.*.list' | sed -n 1p)
}

cache_expired() {
  current_cache=$(current_cache_file | awk -F. '{print $2}')
  [ -z "$current_cache" ] && current_cache=0
  time_diff=$(expr $(date +'%s') - $current_cache)

  if [ "$time_diff" -gt "$TIMEOUT" ]; then
    return 0
  else
    return 1
  fi
}

random_image() {
  # Default to bonespin if the cache has expired, regenerate in the background
  if cache_expired; then
    find /home/clayton/Pictures/Wallpaper -name '*.png' -exec convert "{}" -print "%w:%h:%d/%f\n" /dev/null \; | awk -F: '$1>=1920&&$2>=1080{print $3}' > /tmp/papers.$(date +'%s').list &
    echo $default_img
  fi

  images=$(current_cache_file)
  echo $(shuf $images | head -1)
}

lock() {
  bg_image=$(random_image)
  i3lock -i "$bg_image" -c cccccc -t -e
}

case "$1" in
  lock)
    lock
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    lock && systemctl suspend
    ;;
  hibernate)
    lock && systemctl hibernate
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
  *)
    echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
    exit 2
esac

exit 0
