extends = "../.rumdl.toml"

[global]
exclude = [
  # These are generated files, ignore the issues
  "external/*",
  # Old stuff, no need to modify
  "zArchive",
  # AI Stuff
  "AI Chat/*/artifacts/*",
]
