# create worktrees inside the repo
worktree-path = "{{ repo_path }}/.worktrees/{{ branch | sanitize }}"

[aliases]
l = "wt list --progressive {{ args }}"
s = "wt switch {{ args }}"
c = "wt switch --create {{ args }}"
